version: '3'
services:

  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: 'elasticsearch:6.6.1'
    restart: always
    ports:
      - '9200:9200'
    networks:
      - mariadb_network

  logstash:
    container_name: logstash
    hostname: logstash
    image: 'logstash-mysql-sync'
    restart: always
    build: ./logstash
    networks:
      - mariadb_network
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    hostname: kibana
    image: 'kibana:6.6.1'
    restart: always
    ports:
      - '5601:5601'
    networks:
      - mariadb_network
    depends_on:
      - elasticsearch

networks:
  mariadb_network:
    external:
      name: mariadb_network